### ISSUE TITLE
glastopf-runner error

### ISSUE THREAD

**Issue by cybergroot** [glastopf/glastopf#214]
root@cyberguerrilla:/opt/myhoneypot# glastopf-runner
2015-01-17 01:23:42,530 (glastopf.glastopf) Initializing Glastopf 3.1.3-dev using "/opt/myhoneypot" as work directory.
```
Traceback (most recent call last):
  File "/usr/local/bin/glastopf-runner", line 5, in <module>
    pkg_resources.run_script('Glastopf==3.1.3.dev0', 'glastopf-runner')
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/EGG-INFO/scripts/glastopf-runner", line 83, in <module>
    honeypot = GlastopfHoneypot(work_dir=args.workdir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/glastopf.py", line 64, in __init__
    self.loggers = logging_handler.get_aux_loggers(self.data_dir, self.work_dir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/modules/logging_handler.py", line 49, in get_aux_loggers
    logger_instance = logger_class(data_dir, work_dir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/modules/reporting/auxiliary/log_logstash.py", line 15, in __init__
    if self.config.getboolean("logstash", "enabled"):
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'logstash'
```

**Comment by cybergroot** [comment]
Then I chown'd it I get this error:

root@cyberguerrilla:/opt/myhoneypot# glastopf-runner
2015-01-17 01:39:48,500 (glastopf.glastopf) Initializing Glastopf 3.1.3-dev using "/opt/myhoneypot" as work directory.
Traceback (most recent call last):
  File "/usr/local/bin/glastopf-runner", line 5, in <module>
    pkg_resources.run_script('Glastopf==3.1.3.dev0', 'glastopf-runner')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1614, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/EGG-INFO/scripts/glastopf-runner", line 83, in <module>
    honeypot = GlastopfHoneypot(work_dir=args.workdir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/glastopf.py", line 64, in __init__
    self.loggers = logging_handler.get_aux_loggers(self.data_dir, self.work_dir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/modules/logging_handler.py", line 49, in get_aux_loggers
    logger_instance = logger_class(data_dir, work_dir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/modules/reporting/auxiliary/log_logstash.py", line 15, in __init__
    if self.config.getboolean("logstash", "enabled"):
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'logstash'

**Comment by glaslos** [comment]
Recreate your Glastopf config or add the lines from this section: https://github.com/glastopf/glastopf/blob/master/glastopf/glastopf.cfg.dist#L81

**Comment by xentity** [comment]
@cybergroot : Hi, I think, I opened up an issue to the same thing, look at issue #216 (is closed, too). Sorry, didn't see this issue before.

There was a bug, it is fixed, now. Get the lastest sources from yesterday, then it should start.
