### ISSUE TITLE
No section: 'logstash'

### ISSUE THREAD

**Issue by xentity** [glastopf/glastopf#216]
Hi,

tried to install Glastopf and I am ready, finally.

But if I try to start, I get the following:

admin@server:/opt/myhoneypot$ sudo glastopf-runner
2015-01-19 18:25:00,319 (glastopf.glastopf) Initializing Glastopf 3.1.3-dev using "/opt/myhoneypot" as work directory.
Traceback (most recent call last):
  File "/usr/local/bin/glastopf-runner", line 5, in <module>
    pkg_resources.run_script('Glastopf==3.1.3-dev', 'glastopf-runner')
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3_dev-py2.7.egg/EGG-INFO/scripts/glastopf-runner", line 83, in <module>
    honeypot = GlastopfHoneypot(work_dir=args.workdir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3_dev-py2.7.egg/glastopf/glastopf.py", line 64, in __init__
    self.loggers = logging_handler.get_aux_loggers(self.data_dir, self.work_dir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3_dev-py2.7.egg/glastopf/modules/logging_handler.py", line 49, in get_aux_loggers
    logger_instance = logger_class(data_dir, work_dir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3_dev-py2.7.egg/glastopf/modules/reporting/auxiliary/log_logstash.py", line 15, in __init__
    if self.config.getboolean("logstash", "enabled"):
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'logstash'

I pulled the last version via git, the os is Ubuntu 14.04.1 LTS, the config file is written fine and a logstash section is also in it:
admin@server:/opt/myhoneypot$ grep -n4 logstash glastopf.cfg
77-include_contact_info = False
78-contact_name = ...
79-contact_email = ...
80-
81:[logstash]
82-enabled = False
83-host = localhost
84-port = 5659
85-handler = AMQP/TCP/UDP

What I am doing wrong or is it a bug?

**Comment by johnnykv** [comment]
It was a bug, i don't thing the logstash handler was ever working. Fixed now - not really sure the logstash plugin works - but at least it does not crash....

**Comment by xentity** [comment]
Wow, what a reaction time! Perfectly, works for me!
